name: Download artifact exists
description: Download artifact exists
inputs:
  artifactName:
    description: Artifact name to check
    required: true
  logHeader:
    description: Header for the log
    required: false
runs:
  using: "composite"
  steps:
    - name: Check if artifact exists
      id: check_artifact_exists
      uses: actions/github-script@v7
      with:
        script: |
          const artifactName = '${{ inputs.artifactName }}';
          const runId = process.env.GITHUB_RUN_ID;
          const { data: artifacts } = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: runId,
          });
  
          const artifact = artifacts.artifacts.find(artifact => artifact.name === artifactName);
  
          if (artifact) {
            core.setOutput('artifact_exists', true);
          } else {
            core.setOutput('artifact_exists', false);
          }

    - name: Download artifact if exists
      if: steps.check_artifact_exists.outputs.artifact_exists == 'true'
      uses: actions/download-artifact@v4
      with:
        path: ${{ inputs.artifactName }}
        name: ${{ inputs.artifactName }}

    - name: Read artifact if exists
      if: steps.check_artifact_exists.outputs.artifact_exists == 'true'
      run: |
        if [ -d ${{ inputs.artifactName }} ]; then
            echo -e "${{ inputs.logHeader }}" >> "$RUNNER_TEMP/log.txt"
            for file in ${{ inputs.artifactName }}/*; do
              if [ -f "$file" ]; then
                cat "$file" >> "$RUNNER_TEMP/log.txt"
              fi
            done
            rm -rf ${{ inputs.artifactName }}
          fi
      shell: bash