name: Keboola Storage validation pull
description: Pulling from Keboola project storage structure
inputs:
  destFile:
    description: Destination file
    required: true
  kbcSapiHost:
    description: Keboola Connection Stack URL
    required: true
  kbcSapiToken:
    description: Keboola Connection Storage API Token
    required: true
  kbcProjectId:
    description: Keboola Connection Project ID
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: get random number
      id: random_number
      uses: yakubique/random-number@v1.1
      with:
        min: 1
        max: 1000

    - name: Def out directory
      id: def_dir
      run: |
        echo "OUT_DIR=storage_structure_${{ steps.random_number.outputs.number }}" >> "${GITHUB_ENV}"
      shell: bash

    - name: Pull storage structure
      shell: bash
      run: |
        python .github/actions/kbc_storage_validation/get_storage_structure/scripts/storage_pull.py \
          --host="${{ inputs.kbcSapiHost }}" \
          --project="${{ inputs.kbcProjectId }}" \
          --token="${{ inputs.kbcSapiToken }}" \
          --destination-file="${{ env.OUT_DIR }}/${{ inputs.destFile }}"

    - name: Save structure to artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUT_DIR }}
        path: ${{ env.OUT_DIR }}/*
        retention-days: 1
