name: Manual KBC Pull d
description: Pull configurations from Keboola Connection projects (d)
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Pull_All:
    # Generated value
    environment: |-
      ${{
         github.ref_name == 's' && 's'
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Generated steps 
      - name: Pull configurations from 
        uses: ./.github/actions/kbc_pull
        with:
          workdir: "d"
          kbcStackUrl: ${{ vars.d_STACK_URL }}
          kbcStorageApiToken: ${{ secrets.d_TOKEN }}
          kbcProjectId: ${{ vars.d_PROJECT_ID }}
          kbcBranchId: ${{ vars.d_BRANCH_ID }}
      # End generated steps

      - name: Commit and push
        run: |
          apt-get update && apt-get install -y tree
          tree -a
          currentDate=`date +%Y-%m-%d:%T%Z`
          pull_log=`cat "$RUNNER_TEMP/log.txt"`
          git config --global user.name 'Keboola CLI'
          git config --global user.email 'keboola-cli@users.noreply.github.com'
          git add -A
          git commit -a -m "Manual KBC pull $currentDate" -m "$pull_log" || true
          git push --force