name: Manual KBC Push All
description: Push configurations to Keboola Connection projects (d)
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Push_All:
    # Dynamic generated value
    environment: |-
      ${{
         github.ref_name == 's' && 's'
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Generated steps 
      - name: Push configurations to d
        uses: ./.github/actions/kbc_pull
        with:
          workdir: "d"
          kbcStorageApiToken: ${{ secrets.d_TOKEN }}
          kbcProjectId: ${{ vars.d_PROJECT_ID }}
          kbcBranchId: ${{ vars.d_BRANCH_ID }}
      # End generated steps